# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{style_train}
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Kane Baccigalupi"]
  s.date = %q{2011-02-28}
  s.description = %q{style_train builds CSS using pure Ruby, not a DSL interpreted via Ruby. This allows inheritance, modules, instance level calculations and all the goodness Ruby can offer.}
  s.email = %q{baccigalupi@gmail.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "LISENCE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/style_train.rb",
    "lib/style_train/color.rb",
    "lib/style_train/color_types/color_type.rb",
    "lib/style_train/color_types/hex_color.rb",
    "lib/style_train/color_types/hsl_color.rb",
    "lib/style_train/color_types/keyword_color.rb",
    "lib/style_train/color_types/rgb_color.rb",
    "lib/style_train/sheet.rb",
    "lib/style_train/style.rb",
    "lib/style_train/support/gnash.rb",
    "lib/style_train/support/numbers.rb",
    "lib/style_train/theme.rb",
    "lib/style_train/themed_sheet.rb",
    "research/alexch_color_gist/color.rb",
    "research/alexch_color_gist/color_test.rb",
    "research/contexting.rb",
    "research/overview.txt",
    "research/stylesheet.txt",
    "spec/color/color_spec.rb",
    "spec/color/color_type_spec.rb",
    "spec/color/hex_color_spec.rb",
    "spec/color/keyword_color_spec.rb",
    "spec/color/rgb_color_spec.rb",
    "spec/generated_files/.gitkeep",
    "spec/integration.css",
    "spec/integration_spec.rb",
    "spec/numbers_spec.rb",
    "spec/sheet_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb",
    "spec/style_spec.rb",
    "spec/style_train_spec.rb",
    "spec/theme_spec.rb",
    "spec/themed_sheet_spec.rb",
    "style_train.gemspec"
  ]
  s.homepage = %q{http://github.com/baccigalupi/style_train}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{style_train builds CSS with Ruby}
  s.test_files = [
    "spec/color/color_spec.rb",
    "spec/color/color_type_spec.rb",
    "spec/color/hex_color_spec.rb",
    "spec/color/keyword_color_spec.rb",
    "spec/color/rgb_color_spec.rb",
    "spec/integration_spec.rb",
    "spec/numbers_spec.rb",
    "spec/sheet_spec.rb",
    "spec/spec_helper.rb",
    "spec/style_spec.rb",
    "spec/style_train_spec.rb",
    "spec/theme_spec.rb",
    "spec/themed_sheet_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, [">= 0"])
    else
      s.add_dependency(%q<activesupport>, [">= 0"])
    end
  else
    s.add_dependency(%q<activesupport>, [">= 0"])
  end
end

